2018-06-04 16:41:44,084 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 16:42:06,523 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 17:14:00,434 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 17:21:26,988 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 18:23:59,852 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 19:05:32,463 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 19:08:29,443 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 19:13:28,532 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 19:26:50,430 INFO: Microblog startup [in C:\Users\fanxi\PycharmProjects\狗书\app\__init__.py:50]
2018-06-04 19:27:14,798 ERROR: Exception on /user/yunhua [GET] [in d:\program files\python3_6\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\program files\python3_6\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\program files\python3_6\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\program files\python3_6\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python3_6\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\program files\python3_6\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\program files\python3_6\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\program files\python3_6\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\fanxi\PycharmProjects\狗书\app\routes.py", line 86, in user
    next_url=next_url, prev_url=prev_url)
  File "d:\program files\python3_6\lib\site-packages\flask\templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\program files\python3_6\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python3_6\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\fanxi\PycharmProjects\狗书\app\templates\user.html", line 34, in template
    {% endblock %}
  File "d:\program files\python3_6\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 212, in parse_if
    'name:endif'))
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "d:\program files\python3_6\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
